#!/usr/bin/php
<?php
// @Name: Лизинг DialPlan
// @Author: nenavizhu leto <nenavizhu.leto@gmail.com>
// @Description: Перезагружает dialplan астериска с лизингом

echo "Executing lizing_dialplan_reload.php\n";

$config = (object)[
  "addr" => "172.16.0.20",
  "port" => 62322,
  "user" => "user",
  "password" => "Ccydvbb3qkc@"
];

// $cmd = "asterisk -rx 'dialplan reload'";
//
$cmd = "echo 'hello world'";

echo "Connecting to " . $config->addr . "\n";
$connection = ssh2_connect($config->addr, $config->port);
if (!$connection) {
  echo "Connection failed.\n";
  die(1);
}

if (ssh2_auth_password($connection, $config->user, $config->password)) {
    $stream = ssh2_exec($connection, $cmd);
		stream_set_blocking($stream, true);
		echo stream_get_contents($stream);
		fclose($stream);
}

?>
